/**
 * The `PlatformRenderer` contract (task 6.6, PR B; ADR 0009: "Renderers
 * implement `PlatformRenderer.render(model): RenderedFile[]` and are
 * pure"). Folded into the same commit as the first renderer (task 6.7)
 * rather than committed alone: an interface with zero implementations has
 * no observable behavior to exercise under strict TDD — there is nothing to
 * see RED before the VS Code renderer exists to be GREEN against it.
 *
 * A renderer is a pure function of a `ValidatedModel`: no filesystem, no
 * clock, no environment access, and deterministic output (stable key
 * order, LF-terminated files) for the same input every time. The CLI (task
 * 6.11, PR C) is the only caller that touches `fs`; renderers only ever
 * return in-memory `RenderedFile`s for it to write all-or-nothing.
 */

/**
 * Re-exported from `validate.ts`, which owns both the type and the only
 * function (`assertValidated`) allowed to construct one — see that module
 * for the nominal-brand rationale. Renderers and their tests import it from
 * here, where the rest of the `PlatformRenderer` contract already lives.
 */
import type { ValidatedModel } from "../validate.js";
export type { ValidatedModel };

/** One file a renderer wants written, relative to the repository root. */
export interface RenderedFile {
  /** Repository-relative, POSIX-separated (e.g. `.claude/agents/triage.md`). */
  readonly path: string;
  readonly contents: string;
}

export type PlatformId = "vscode" | "claude-code" | "opencode";

export interface PlatformRenderer {
  readonly platform: PlatformId;
  render(model: ValidatedModel): readonly RenderedFile[];
}

/**
 * Every generated Markdown file's "do not hand-edit" marker (task 6.6:
 * "include a header comment/marker in every generated file"), placed as an
 * HTML comment on the line right after the closing frontmatter `---` so it
 * renders invisibly wherever the file is previewed as Markdown. JSON
 * outputs (`.vscode/mcp.json`, `.mcp.json`, `opencode.json`) intentionally
 * carry no such marker: JSON has no comment syntax, and inventing an
 * undocumented top-level field risks a platform's own schema validator
 * flagging or stripping an unknown key — the drift check (task 6.12, PR C)
 * is what actually catches a hand-edited generated file, marker or not.
 */
export const GENERATED_FILE_MARKER = "<!-- Generated by `npm run generate`. Do not edit by hand. -->";

/**
 * Guards the one invariant every `PlatformRenderer` must hold on its own
 * output: no two `RenderedFile`s it returns ever share a `path`. A
 * duplicate agent/prompt id, or one colliding with a renderer's own
 * reserved synthetic id (`RESERVED_IDS` in `validate.ts`), is already
 * rejected by `validateModel` before a renderer ever runs — but that is a
 * fact about *validated input*, not a proof about renderer *output*: a
 * future renderer change (a new synthesized file, a typo'd literal path)
 * could still reintroduce a collision validation has no way to see. Every
 * renderer calls this on its own output before returning it, so a
 * collision fails loudly here instead of silently letting one file
 * overwrite another's contents once the CLI (task 6.11) writes them to
 * disk.
 */
export function assertNoDuplicatePaths(files: readonly RenderedFile[], rendererName: string): void {
  const seen = new Set<string>();
  for (const file of files) {
    if (seen.has(file.path)) {
      throw new Error(`${rendererName}: duplicate rendered file path "${file.path}"`);
    }
    seen.add(file.path);
  }
}
