import type { GeneratorModel } from "../definitions/schema.js";

/**
 * The `PlatformRenderer` contract (task 6.6, PR B; ADR 0009: "Renderers
 * implement `PlatformRenderer.render(model): RenderedFile[]` and are
 * pure"). Folded into the same commit as the first renderer (task 6.7)
 * rather than committed alone: an interface with zero implementations has
 * no observable behavior to exercise under strict TDD — there is nothing to
 * see RED before the VS Code renderer exists to be GREEN against it.
 *
 * A renderer is a pure function of a `ValidatedModel`: no filesystem, no
 * clock, no environment access, and deterministic output (stable key
 * order, LF-terminated files) for the same input every time. The CLI (task
 * 6.11, PR C) is the only caller that touches `fs`; renderers only ever
 * return in-memory `RenderedFile`s for it to write all-or-nothing.
 */

/**
 * `validateModel`'s two outputs a renderer actually needs: the schema- and
 * graph-checked model itself, and the handoff graph's longest path (edges),
 * which the Claude Code renderer (task 6.8) uses to state its driver
 * command's numeric hard-stop bound. Bundling them (rather than having a
 * renderer re-import `validateModel` and re-run it) keeps a renderer honest
 * that it must only ever run on an already-`ok: true` result — there is no
 * way to construct a `ValidatedModel` from an invalid one without going
 * through `validate.ts` first.
 */
export interface ValidatedModel {
  readonly model: GeneratorModel;
  readonly longestHandoffPath: number;
}

/** One file a renderer wants written, relative to the repository root. */
export interface RenderedFile {
  /** Repository-relative, POSIX-separated (e.g. `.claude/agents/triage.md`). */
  readonly path: string;
  readonly contents: string;
}

export type PlatformId = "vscode" | "claude-code" | "opencode";

export interface PlatformRenderer {
  readonly platform: PlatformId;
  render(model: ValidatedModel): readonly RenderedFile[];
}

/**
 * Every generated Markdown file's "do not hand-edit" marker (task 6.6:
 * "include a header comment/marker in every generated file"), placed as an
 * HTML comment on the line right after the closing frontmatter `---` so it
 * renders invisibly wherever the file is previewed as Markdown. JSON
 * outputs (`.vscode/mcp.json`, `.mcp.json`, `opencode.json`) intentionally
 * carry no such marker: JSON has no comment syntax, and inventing an
 * undocumented top-level field risks a platform's own schema validator
 * flagging or stripping an unknown key — the drift check (task 6.12, PR C)
 * is what actually catches a hand-edited generated file, marker or not.
 */
export const GENERATED_FILE_MARKER = "<!-- Generated by `npm run generate`. Do not edit by hand. -->";
