import { z } from "zod";
import {
  CATEGORY_SUBCATEGORIES,
  isSubcategoryOfCategory,
} from "./categories.js";

const CATEGORY_VALUES = Object.keys(CATEGORY_SUBCATEGORIES) as [
  keyof typeof CATEGORY_SUBCATEGORIES,
  ...Array<keyof typeof CATEGORY_SUBCATEGORIES>,
];

const SUBCATEGORY_VALUES = Object.values(CATEGORY_SUBCATEGORIES).flat() as [
  string,
  ...string[],
];

const LEVEL_VALUES = ["high", "medium", "low"] as const;

/**
 * `New -> Triaged`. Strict (closed-object): rejects `priority` and any
 * other server-computed field, per spec-v2's "Triaged Payload Rejects
 * Server-Computed Fields" requirement (override #2). `subcategory` must
 * belong to `category` (refine).
 */
export const TriagedPayloadSchema = z
  .object({
    category: z.enum(CATEGORY_VALUES),
    subcategory: z.enum(SUBCATEGORY_VALUES),
    severity: z.enum(LEVEL_VALUES),
    urgency: z.enum(LEVEL_VALUES),
    affectedUser: z.string().min(1).max(128),
    impactedService: z.string().min(1),
    summary: z.string().min(1).max(500),
  })
  .strict()
  .refine(
    (payload) =>
      isSubcategoryOfCategory(
        payload.category,
        payload.subcategory as never,
      ),
    {
      path: ["subcategory"],
      message: "subcategory does not belong to the supplied category",
    },
  );
export type TriagedPayload = z.infer<typeof TriagedPayloadSchema>;

/** `Triaged -> InProgress` / `Reopened -> InProgress`. */
export const InProgressPayloadSchema = z
  .object({
    note: z.string().max(500).optional(),
  })
  .strict();
export type InProgressPayload = z.infer<typeof InProgressPayloadSchema>;

const DiagnosticEvidenceRefSchema = z
  .object({
    runId: z.string().min(1),
  })
  .strict();

/** `InProgress -> PendingUserConfirmation`. */
export const PendingUserConfirmationPayloadSchema = z
  .object({
    diagnosticEvidence: DiagnosticEvidenceRefSchema,
    remediationAction: z.string().min(1).nullable(),
    timestamp: z.iso.datetime(),
  })
  .strict();
export type PendingUserConfirmationPayload = z.infer<
  typeof PendingUserConfirmationPayloadSchema
>;

const ESCALATION_REASON_VALUES = [
  "diagnostic_failed",
  "service_unreachable",
  "not_allowlisted",
  "no_diagnostic_available",
  "user_not_fixed",
  "user_request",
] as const;

const ESCALATION_TARGET_VALUES = [
  "identity-team",
  "desktop-support",
  "network-team",
  "access-management",
] as const;

/**
 * `InProgress -> Escalated` / `PendingUserConfirmation -> Escalated`.
 * `decisionLogRef` is generated by the server (the created audit entry's
 * id) and is never a client-accepted input field — spec-v2 corrects the
 * earlier design draft that allowed it as an optional input; `.strict()`
 * rejects it here.
 */
export const EscalatedPayloadSchema = z
  .object({
    escalationReason: z.enum(ESCALATION_REASON_VALUES),
    target: z.enum(ESCALATION_TARGET_VALUES),
    note: z.string().max(500).optional(),
  })
  .strict();
export type EscalatedPayload = z.infer<typeof EscalatedPayloadSchema>;

const RESOLUTION_BASIS_VALUES = [
  "user-confirmed",
  "auto-timeout",
  "human-agent",
] as const;

/**
 * `PendingUserConfirmation -> Resolved` / `Escalated -> Resolved`. Which
 * `basis` values are actually reachable from which source state is a
 * business rule enforced by `resolution-rule.ts`'s `canResolve`, not by
 * this structural schema (design's payload table models `Resolved` as one
 * target-state row).
 */
export const ResolvedPayloadSchema = z
  .object({
    basis: z.enum(RESOLUTION_BASIS_VALUES),
    diagnosticEvidence: DiagnosticEvidenceRefSchema.optional(),
    timestamp: z.iso.datetime(),
  })
  .strict();
export type ResolvedPayload = z.infer<typeof ResolvedPayloadSchema>;

const CONFIRMATION_SOURCE_VALUES = ["user", "auto-timeout"] as const;

/** `Resolved -> Closed`. */
export const ClosedPayloadSchema = z
  .object({
    resolutionSummary: z.string().min(1).max(500),
    confirmationSource: z.enum(CONFIRMATION_SOURCE_VALUES),
  })
  .strict();
export type ClosedPayload = z.infer<typeof ClosedPayloadSchema>;

/** `Resolved -> Reopened` / `Closed -> Reopened` (actor MUST be `user`). */
export const ReopenedPayloadSchema = z
  .object({
    reopenReason: z.string().min(1).max(500),
    originalResolutionRef: z.string().min(1),
  })
  .strict();
export type ReopenedPayload = z.infer<typeof ReopenedPayloadSchema>;
